### ISSUE TITLE
AMD Radeon Pro Vega 20 (Aka vega12)

### ISSUE THREAD

**Issue by RodrigoLuglio** [M-Bab/linux-kernel-amdgpu#10]
I have a macbook pro with vega 20 which uses the amdgpu firmware vega12 and when i boot any distro the graphics glitch and the computer freezes. If i install amdgpu pro on ubuntu it works flawlessly. Would you guys help me debug this and fix for upstream? 
I would be very glad to help debug and collaborate to find the fix, if i may.
Please, excuse me if this is not the right place for me to ask this kind of thing, and please if you can, kindly redirect me to the right place.

**Comment by M-Bab** [comment]
I guess this is outdated by now. You can retry with 5.13 and reopen if the problem persists.

**Comment by RodrigoLuglio** [comment]
It still persist on 5.15.12.

**Comment by RodrigoLuglio** [comment]
It works when I use amdgpu.ppfeaturemask=0xF7FFF. Any value above that I get the same issue.

**Comment by M-Bab** [comment]
So you are not actually using the kernels build from this repository (https://github.com/M-Bab/linux-kernel-amdgpu-binaries) ?

**Comment by RodrigoLuglio** [comment]
No, um not, my apologies for the mess up. I’m really sorry. 
I have to apply some patches to the kernel myself so I can boot in my MacBook pro. These patches are enables the t2 chip to work with Linux. Is there any chance I can get your patches to apply together with mine?
