### ISSUE TITLE
Interlacing, duplicated pixels after suspending or hibernating

### ISSUE THREAD

**Issue by auroraanna** [M-Bab/linux-kernel-amdgpu#11]
When I suspend or hibernate my computer and then boot it back up there is a section on my monitor being weirdly interlaced with some parts duplicated. See it yourself in the attached video. Rebooting fixes it. I have an AMD Radeon R9 280X graphics card and this only happens with the *amdgpu* driver, not with the *radeon* driver. The can be said for the AMD Radeon HD 7850 I had installed previously. This only affects one of my three monitors, which is plugged in via Displayport 1.2. Switching the cable doesn't help so I suppose it's a driver issue.

*Update*: This occurs if I turn off my monitor and then turn it on again too. It also doesn't occur in BIOS, just when Linux is booted.

https://user-images.githubusercontent.com/81317317/128265867-94209606-bbe9-40b5-90c1-92acf29340d2.mp4

**Comment by M-Bab** [comment]
I guess this is outdated by now. You can retry with 5.13 and reopen if the problem persists.
