### ISSUE TITLE
How to enable DC/DAL features in the Kernel ?

### ISSUE THREAD

**Issue by Bulbyzarr** [M-Bab/linux-kernel-amdgpu#2]
Hi,

I'm interested to build the latest amd-staging kernel 4.11 on Gentoo and i need your help. Which are the options must be to enable in the amd-staging kernel to have DC/DAL features working for my Rx560 ? 

Thanks,

**Comment by M-Bab** [comment]
Hi Maxime, 

Have a look at the .config file in this source tree, the most important settings are all in one place :

Build the amdgpu module for all available generations :
CONFIG_DRM_AMDGPU=m CONFIG_DRM_AMDGPU_SI=y CONFIG_DRM_AMDGPU_CIK=y 
(You won't need the last 2 for rx560) 

Build the audio Co processor driver
CONFIG_DRM_AMD_ACP=y
(If you ultimately need this depends on your specific card) 

Build the DC display code for all available generations 
CONFIG_DRM_AMD_DC=y CONFIG_DRM_AMD_DC_DCN1_0=y
(You won't need the last one for rx560) 

You can also start with my .config file and adjust it to your needs.
Or when you start with any other .config file and do a "make oldconfig" it will ask you for only the new settings from the amd-staging kernel. 

Good luck! 

________________________________
Von: Babaorhum <notifications@github.com>
Gesendet: 05.08.2017 11:17 vorm.
An: M-Bab/linux-kernel-amdgpu
Cc: Subscribed
Betreff: [M-Bab/linux-kernel-amdgpu] How to enable DC/DAL features in the Kernel ? (#2)

**Comment by Bulbyzarr** [comment]
EDIT : Was my fault, i booted on the wrong kernel ... -_-'

But i have a negative point : 
When i have sound on my TV via HDMI, when i plug my headphone, there is no automatic switch.
I must to reload the video on youtube (F5) or quit/re-launch VLC to have the sound in the headphone.

**Comment by M-Bab** [comment]
Maybe I have a solution for you (if you are using pulseaudio):
In /etc/pulse/default.pa replace
```
< load-module module-stream-restore
---
> load-module module-stream-restore restore_device=false
```
after that "pulseaudio -k" and you are ready to go.

If you (like me) regularly switch audio outputs you might love that little utility 
https://github.com/M-Bab/home_dotfiles/blob/master/bin/mypa
Run it with "mypa gui". I actually placed that on my Super+A keyboard shortcut.

**Comment by Bulbyzarr** [comment]
Thanks M-Bab,

I'll try that when i'm back at home. 

Other question about your git repo. How do you do to clone the amdgpu-staging 4.11 branch from https://cgit.freedesktop.org/~agd5f/linux/ ?

On Gentoo, i try to clone the amd-staging-4.12 branch without success. I have only the possibility to download all git repo ... not only one branch.

**Comment by M-Bab** [comment]
Maybe something like: https://stackoverflow.com/questions/4811434/clone-only-one-branch

git clone is as the name says always a copy of a whole repo. It is always a huge load of data. That's one drawback of a distributed version control system.
