### ISSUE TITLE
Would this work with Fedora 26?

### ISSUE THREAD

**Issue by ki4jgt** [M-Bab/linux-kernel-amdgpu#3]
Would this work with Fedora 26? Would the binaries be better? Are there any special instructions?

**Comment by M-Bab** [comment]
If you compile this source tree on fedora it should work, yes. Right now I would recommend the mbab_4.12 branch. Something like "make rpm" is your friend here. For detailed instructions how to build a custom kernel on fedora, google will find you some instructions.

The binaries are specifically for Debian, Ubuntu and Derivates and I would not risk it to install it on a distribution that does not use dpkg packages.

BUT good news: mystro256 builds ready to use kernel binaries for fedora:
https://copr.fedorainfracloud.org/coprs/mystro256/amd-staging-kernel/
As always: Use cautiously, it is a bleeding-edge kernel from a random guy of the internet. I can't undertake for this kernel but the mystro binaries also have a couple of users. Read the instructions https://github.com/M-Bab/linux-kernel-amdgpu-binaries for more information (e.g. where to get the firmware blobs)
