### ISSUE TITLE
4.15 branch

### ISSUE THREAD

**Issue by gregorlarson** [M-Bab/linux-kernel-amdgpu#5]
I noticed you posted some 4.15 binaries at:
https://github.com/M-Bab/linux-kernel-amdgpu-binaries
Would it be possible to see your 4.15 branch here?
Thanks,
- Greg

**Comment by M-Bab** [comment]
Done.

Yeah that was missing somehow. Thanks for the reminder it is actually worth putting the source code as well because merging the RC code with the latest amd-staging-drm-next was a bit tricky.
