### ISSUE TITLE
Duplicate.

### ISSUE THREAD

**Issue by ddobreff** [M-Bab/linux-kernel-amdgpu#6]
https://github.com/M-Bab/linux-kernel-amdgpu/blob/7d9b9460d5ddeb56b0d18a698a6b916629b9a985/security/apparmor/include/audit.h#L140

**Comment by M-Bab** [comment]
Yeah the code got screwed up in all the merges. Ubuntu unstable didnt update the kernel for a while and now they jumped to 4.17 so I drop the Ubuntu variant for the moment.
