### ISSUE TITLE
What are the ways to control AMD Radeon HD 7670M performance?

### ISSUE THREAD

**Issue by BoQsc** [M-Bab/linux-kernel-amdgpu#8]
I'm really unsure if this the right place to ask, just point me to the right place, if that is the case.

I have a Laptop AMD Radeon HD 7670M GPU and would like to slow it down. 
Is there a way to configure it? Internet is kind of bloated with unfunctional examples.

**Comment by M-Bab** [comment]
This always happens via the path /sys/class/drm/card0/device

Have a look at these two pages:
* https://wiki.archlinux.org/index.php/AMDGPU#Overclocking
* https://linuxconfig.org/overclock-your-radeon-gpu-with-amdgpu

And always remember overclocking is like underclocking just in the other direction.
