### ISSUE TITLE
Build configs

### ISSUE THREAD

**Issue by Legogris** [M-Bab/linux-kernel-amdgpu#9]
@M-Bab Really appreciate you putting this together! I wonder if you'd be able to put the configs used to compile the releases in https://github.com/M-Bab/linux-kernel-amdgpu-binaries either here or in that repo? Would facilitate verifying the builds and external contributions.

**Comment by M-Bab** [comment]
They are already there: it is the .config file available in the root directory of each branch in this repo.

Have fun!
